name: veille_emploi
description: Application mobile pour la recherche d'emploi au Bénin.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.5.0
  url_launcher: ^6.2.5
  intl: ^0.19.0
  timeago: ^3.6.1
  carousel_slider: ^4.2.1
  shared_preferences: ^2.2.2
  firebase_core: ^3.1.1
  firebase_messaging: ^15.0.1
  share_plus: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

# 👇 LE COUP DE GRÂCE : On force l'utilisation d'un plugin neuf sans bug !
dependency_overrides:
  package_info_plus: ^8.0.0
