name: 📱 Fabriquer l'Application Mobile

on:
  workflow_dispatch: # Se lance uniquement à la main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Récupération du code
      uses: actions/checkout@v4

    - name: ⚙️ Configuration de Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: 🦋 Installation de Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version: '3.22.0'

    - name: 🔨 Construction du projet magique
      run: |
        flutter create build_temp
        cp app_mobile/pubspec.yaml build_temp/
        rm -rf build_temp/lib/*
        cp -r app_mobile/lib/* build_temp/lib/
        cd build_temp
        flutter pub get
        flutter build apk --release

    - name: 📦 Mise à disposition de l'application
      uses: actions/upload-artifact@v4
      with:
        name: Veille_Emploi_App
        path: build_temp/build/app/outputs/flutter-apk/app-release.apk
